version: '3.8'

services:
  chroma-server:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - ./vector-db:/chroma/chroma  # Если vector-db в корневой папке проекта
      # - ./backend/vector-db:/chroma/chroma  # Если vector-db внутри папки backend
    ports:
      - "8000:8000"
    networks:
      - chroma-net

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - CHROMA_SERVER_HOST=chroma-server
      - CHROMA_SERVER_HTTP_PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - chroma-server
    networks:
      - chroma-net

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - chroma-net

networks:
  chroma-net:
    driver: bridge
